version: "3.7"
services:
  web:
    build: .
    restart: always
    env_file: dev.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    env_file:
      - dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
