# Generated by Django 5.0.6 on 2024-05-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.location'),
        ),
    ]
