# Generated by Django 5.0.6 on 2024-06-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weather', serialize=False, to='todolist.location')),
                ('temperature', models.FloatField()),
                ('status', models.CharField(max_length=500)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
