# Generated by Django 5.0.6 on 2024-06-03 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastWeatherRead',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='last_weather_read', serialize=False, to='todolist.task')),
                ('temperature', models.FloatField()),
                ('status', models.CharField(max_length=500)),
            ],
        ),
    ]
